### ISSUE TITLE
Listing 6.27 failed for me

### ISSUE THREAD

**Issue by dirschn** [mhartl/sample_app_6th_ed#49]
Hi there, when using the code in listing 6.27 I ran into a syntax error. The code you have in the tutorial is written as: 
`uniqueness: case_sensitive: false`

I was able to fix the issue by using:

`uniqueness: { case_sensitive: false }`

which caused the tests to pass. I'm not sure if it's the difference between an update in Rails since when you first uploaded the tutorial or not, but I figured I'd let you know.

**Comment by mhartl** [comment]
Thanks for the report. Where are you seeing `uniqueness: case_sensitive: false`? That’s not how it appears in the book:
<img width="752" alt="Screen Shot 2021-12-28 at 11 39 26 AM" src="https://user-images.githubusercontent.com/6232/147601293-18037fa6-7b43-466d-9403-e289c325a53f.png">

**Comment by dirschn** [comment]
![image](https://user-images.githubusercontent.com/25785789/147601696-ab5434cf-fbf8-49fa-926d-be0ffe98f9ba.png)

I'm using the version on learning.oreilly.com, which shows this. It might also be worth mentioning that the Gemfiles haven't updated on this version, compared to what is on the github that is linked in the tutorial, even though it says they should be updated when reading online. Maybe O'Reilly isn't updating the book?

**Comment by mhartl** [comment]
OK, I have limited control over that copy of the book. I’ll forward this to my contact at O’Reilly and hope they can update it.

You’re right about the Gemfiles. It’s probably not worth fixing for the 6th edition because the text does say explicitly to use the ones at gemfiles-6th-ed.railstutorial.org, but for the next edition I’ll change “reading this online” to “reading this at railstutorial.org or learnenough.com”.

**Comment by dirschn** [comment]
Okay, that's what I figured. Thanks for responding!

**Comment by mhartl** [comment]
If you find any other discrepancies, please do let me know. Make sure to remind me that you’re using the version at oreilly.com; statements like “The code you have in the tutorial is written as” can be confusing for me since the version I have personally written is the one at railstutorial.org/learnenough.com.

**Comment by dirschn** [comment]
Okay, that's good to know and makes a lot of sense. Will do!
